version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/input.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_measures:
    run: ehrql:v1 generate-measures analysis/measure_definition.py --output output/measures.csv
    outputs:
      moderately_sensitive:
        measures: output/measures.csv

  test_function:
    run: python:latest analysis/plot_measures.py
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        df: test_output.csv
        figure: example_gifure.png
